### ISSUE TITLE
Table duplicated

### ISSUE THREAD

**Issue by giann** [bakpakin/binser#10] opened 2018-09-22 21:52 UTC
I'm trying to serialize a rather complex and large table. Good news is, binser is really fast to do so.
Bad news is there's some self-referencing that it doesn't seem to recognize.

I have a hierarchy like so:
```
level -> grid[x][y] -> units[x] -> actions[i] -> data -> level
```
Where `level` should be equal to `data.level`. I get two copies of the same `level`.

**Comment by giann** [comment] 2018-09-22 22:43
That's what I'm trying to do. But every snippet I write doesn't reproduce the issue.
Looking at binser.lua I also don't see the issue, you follow somewhat the same algorithm that I use [here](https://github.com/giann/save-lua) for the serialization part. Maybe the issue is in the deserialization.

**Comment by bakpakin** [comment] 2018-09-22 22:50
If you are using custom types (registering classes) try disabling that. Resources are probably alright.

**Comment by giann** [comment] 2018-09-22 23:02
I'm registering [hump](https://github.com/vrld/hump) classes with `binser.register(class, name)`. Without those I run in an error the first time one of the deserialized table is used because of missing functions.

**Comment by bakpakin** [comment] 2018-09-22 23:06
I have just found a bug involving serializing the string “next”. It would have messed up references when serializing and could maybe cause behavior like you are describing. I have pushed a fix on the branch fix-next, so you may want to check that out.

**Comment by giann** [comment] 2018-09-22 23:16
I get the following error on serialization:
```
Error: lib/binser.lua:254: Infinite loop in constructor.
stack traceback:
        lib/hump/gamestate.lua:103: in function 'handler'
        [string "boot.lua"]:637: in function <[string "boot.lua"]:633>
        [C]: in function 'error'
        lib/binser.lua:254: in function 'check_custom_type'
        lib/binser.lua:288: in function <lib/binser.lua:283>
        lib/binser.lua:308: in function <lib/binser.lua:283>
        lib/binser.lua:263: in function 'check_custom_type'
        lib/binser.lua:288: in function <lib/binser.lua:283>
        lib/binser.lua:263: in function 'check_custom_type'
        ...
        lib/binser.lua:288: in function <lib/binser.lua:283>
        lib/binser.lua:296: in function <lib/binser.lua:283>
        lib/binser.lua:308: in function <lib/binser.lua:283>
        lib/binser.lua:412: in function 'serialize'
        src/game.lua:270: in function 'save'
        src/game.lua:492: in function '__NULL__'
        lib/hump/gamestate.lua:120: in function 'update'
        [string "boot.lua"]:509: in function <[string "boot.lua"]:493>
        [C]: in function 'xpcall'
```

**Comment by giann** [comment] 2018-09-22 23:36
Something's fishy with the `visited` table: i printed the value of visited[x] any time the key of a table was "level":
```
visited[level]  level
35070           table: 0x111d50c8
35070           table: 0x111d50c8
35070           table: 0x111d50c8
35070           table: 0x111d50c8
35070           table: 0x111d50c8
35070           table: 0x111d50c8
38049           table: 0x111d50c8
58665           table: 0x111d50c8
74928           table: 0x111d50c8
```
So the same value is at 3 different indexes.

**Comment by giann** [comment] 2018-09-22 23:57
I think I found the issue in [`check_custom_type`](https://github.com/bakpakin/binser/blob/master/binser.lua#L251-L261). You're serializing the content of the `x` before defining `visited[x]`. In my case, `x` contains self references and since `visited[x]` is not yet defined, we get several copies of `x`. Just can't quite understand why this doesn't go in infinite loop.

**Comment by bakpakin** [comment] 2018-09-23 00:28
Have you defined level to be a custom type? If so, you may need to rethink something. A custom type cannot have itself be a parameter to its own constructor. Hence the error. The old code had an error that wasn't throwing the exception in all cases.

This limitation is to prevent something like the following:

```lua
local myType_index = {}
local myType_mt = {name="MyType", _index=myType_index}

-- This would cause infinite recursion, and just doesn't make sense.
function myType_mt:_serialize()
    return self
end

-- Also doesn't make much sense.
function myType_mt.deserialize(x)
    return x
end
```
There are some technical reasons why we can't resolve the cycles for custom types, like we can for normal tables. Basically, we can't resolve references to a custom type inside it's constructor because we haven't constructed it yet! For tables, we create the table before we started adding its contents, and simply insert values into the table as we "construct" it.

**Comment by giann** [comment] 2018-09-23 00:41
It's a custom type instance that holds reference to itself.

An instance of _Level_ contains an array of _Unit_. Those _Unit_ instances can have references to the _Level_ instance that holds them.

Since the _Level_ instance is not yet registered in `visited` when its content is being serialized, that _Level_ instance is serialized several times.

The fix in [my pr](https://github.com/bakpakin/binser/pull/11) solves the issue for me.

I'm not sure what you are refering to as a _constructor_. You seem to consider that the elements of a class instance are the parameters to pass to its constructor?

**Comment by bakpakin** [comment] 2018-09-23 00:58
By constructor, I mean the deserialize method for the class.

>Since the Level instance is not yet registered in visited when its content is being serialized, that Level instance is serialized several times.

And that is by design. For example, say binser is trying to serialize a _Level_. With your PR, binser will
mark the level as seen and then call the custom serializer, and serialize that result instead. So far, so good, no double serialization of the _Level_. When deserializing however, binser will be unable to resolve the references in _Unit_ pointing back to the original _Level_, because at that point in time, _Level_ has not been constructed yet.

>The fix in my pr solves the issue for me both at serialization and deserialization.

Sort of, and seems to cause a number of other problems.

**Comment by giann** [comment] 2018-09-23 01:06
Deserialization is ok because I initialize the Level instance as an empty table before deserializing its content and finally calling the constructor with the instance and its content as parameters.

**Comment by bakpakin** [comment] 2018-09-23 01:10
Creating an empty table first and adding things to that will not work in the general case, when we are trying to define custom serializers for userdata.

However, if we have a slightly different serialization/deserializtion path for userdata, such a method should work.

**Comment by giann** [comment] 2018-09-23 01:11
A custom type instance should be able to hold a reference to itself. At least for simple tables/metatables.

Maybe it’s possible to handle both cases ?

**Comment by bakpakin** [comment] 2018-09-23 01:18
I think it should be. `check_custom_type` could check if x was a normal table or userdata, and add x to the `visited` table before recursing in the table case, and after rscursing in the userdata case. Perhaps we would also need a different prefix byte for each case, say byte \209 (the current byte prefix) for tables, and byte \213 for userdata.

For deserialization, we could basically do the old behavior for userdata, and the new behavior for tables. This shouldn't complicate things too much I can't think of any issues.

**Comment by bakpakin** [comment] 2018-09-23 01:29
In the meantime, just use `binser.registerResource` on the metatable of Level and Unit. This is probably semantically closer to what you want.

**Comment by bakpakin** [comment] 2018-09-28 14:28
So after I revisited the code ( I admit I haven't touched this code for a while), I see that the metatables of a table were not serialized unless the metatable was registered as a class. With this new change (commit 11da66fbb87bd809627ae2f7009173a0315bdf7f ), the metatable will properly serialize, and the technique I mentioned above should work. Sorry for the confusion.

**Closed** 2018-09-29 15:39 UTC
